<?php

declare(strict_types=1);

namespace frontend\modules\api\v1;

class Module extends \yii\base\Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}